{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minestom",
    "module": "minestom",
    "version": "dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.1.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-ansi",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "minestom-dev.jar",
          "url": "minestom-dev.jar",
          "size": 4262054,
          "sha512": "8105198e584a275f9178cabaa90d6f255c1119dc26d290ccd42d66211c03d8fd8c86a9f0158238147b0782bb1265714bb7b374a3c8256fe7106e153f61492b36",
          "sha256": "3e5578be519a84169a4f03f059ec5a20a2ea05daf0dbfa7a30d250ffb674e20f",
          "sha1": "c3f8498d87230beff06acd2c790808cdd26a11e3",
          "md5": "290221b0174949c4f74409b9a2fa4530"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.18"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.19"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "space.vectrix.flare",
          "module": "flare",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "space.vectrix.flare",
          "module": "flare-fastutil",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "org.jctools",
          "module": "jctools-core-jdk11",
          "version": {
            "requires": "4.0.7"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.1.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-ansi",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.flowstom",
          "module": "nightstorm-data",
          "version": {
            "requires": "2026.09.12-26.3-rc-3"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "minestom-dev.jar",
          "url": "minestom-dev.jar",
          "size": 4262054,
          "sha512": "8105198e584a275f9178cabaa90d6f255c1119dc26d290ccd42d66211c03d8fd8c86a9f0158238147b0782bb1265714bb7b374a3c8256fe7106e153f61492b36",
          "sha256": "3e5578be519a84169a4f03f059ec5a20a2ea05daf0dbfa7a30d250ffb674e20f",
          "sha1": "c3f8498d87230beff06acd2c790808cdd26a11e3",
          "md5": "290221b0174949c4f74409b9a2fa4530"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minestom-dev-sources.jar",
          "url": "minestom-dev-sources.jar",
          "size": 1529659,
          "sha512": "bb20e07ba0dfeec29728e532f9257c2c000a0c78b4f376ad3d7738fd4236c69cfa654cd263f4c2b1fd1883ae4913ef9044970c441aaf1fc0edd13e046577d28b",
          "sha256": "31221a240da1856df029cdacedd6598826d50b9acb4c1bed3cd8f440834dadf7",
          "sha1": "94308672e04ca6d4923742402e232ca2bd74ce61",
          "md5": "53dd76edc70836a3638e8b68f1e981b5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minestom-dev-javadoc.jar",
          "url": "minestom-dev-javadoc.jar",
          "size": 14021893,
          "sha512": "4f3367d0086ca4d31813e8fd0bc524ff09a75601d69806d4cf4875f03355d54c341e6c829d0676b00260d92cb89c96826144ce6af9e19248b172c18d4ad664dd",
          "sha256": "7d8d474f5a7c3ed934368fb606ad519dca2c47e50551adb2fcd4829bfd5e8ca7",
          "sha1": "19fa4ad3715af5b0eeb00c2c77a34fec74f0a5c0",
          "md5": "1ada803e06f3040eb869b66e4c2e02c9"
        }
      ]
    }
  ]
}
