{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minestom",
    "module": "minestom",
    "version": "dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.1.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-ansi",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "minestom-dev.jar",
          "url": "minestom-dev.jar",
          "size": 4255206,
          "sha512": "dc5565ab056eff2b70690b40c36894ee50da1364bf81e0d6b291b6458ef7cc1c935017b183aac2c6c2ec3340cb75a4786e1402f1a65baf40e3f9a9e596376ecd",
          "sha256": "c2e748c9490527af5262408c87d6504cbce7dc51177259d3841b76f0117b2d4a",
          "sha1": "7cc8fd00fe02caf6820fa6b58775295d7105c0ab",
          "md5": "ac667619055434e6b61dbd659bc694e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.18"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.19"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "space.vectrix.flare",
          "module": "flare",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "space.vectrix.flare",
          "module": "flare-fastutil",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "org.jctools",
          "module": "jctools-core-jdk11",
          "version": {
            "requires": "4.0.7"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.1.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-ansi",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.flowstom",
          "module": "nightstorm-data",
          "version": {
            "requires": "2026.08.28-26.3-rc-2"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "minestom-dev.jar",
          "url": "minestom-dev.jar",
          "size": 4255206,
          "sha512": "dc5565ab056eff2b70690b40c36894ee50da1364bf81e0d6b291b6458ef7cc1c935017b183aac2c6c2ec3340cb75a4786e1402f1a65baf40e3f9a9e596376ecd",
          "sha256": "c2e748c9490527af5262408c87d6504cbce7dc51177259d3841b76f0117b2d4a",
          "sha1": "7cc8fd00fe02caf6820fa6b58775295d7105c0ab",
          "md5": "ac667619055434e6b61dbd659bc694e0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minestom-dev-sources.jar",
          "url": "minestom-dev-sources.jar",
          "size": 1527744,
          "sha512": "8cd393595195be4610a4aeab6d7aa26d0b907837e1c04d6416a84c1ac9c44ac6cca8121de7650bcbad3e23e16b31d233e2f4b4aca11acdc12ce28169c9ac40a5",
          "sha256": "88b9ea135f55e4a7fb1d889349f032c14e9e45efe660b93a599b2859f0f05011",
          "sha1": "987601916a1e1d10945444cf62fc3d148db76842",
          "md5": "02ee4eb3710aff0dbbd1ea26a2802a1e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minestom-dev-javadoc.jar",
          "url": "minestom-dev-javadoc.jar",
          "size": 14015260,
          "sha512": "c90b4c80cf4665ebf36bd920a20c8791022ccebcb3318476c6a07a57fcced4e458b0dcb5076320f452270307225f0592dee74565eaa6b1b5ec51ea3ad85d4037",
          "sha256": "0b502d20e2779be641423ff65cbe0b86c7361d372c48bffc29f69c297f97a46b",
          "sha1": "8c34fc6587bcd2e6240875465934e9b711e470c0",
          "md5": "dc7270180561881ae503ad80d1b95dca"
        }
      ]
    }
  ]
}
