package net.minestom.server;

import net.minestom.server.utils.MajorMinorVersion;

/**
 * This class contains all the generated constants for {@link MinecraftServer}
 * <br>
 * Code autogenerated, do not edit!
 */
sealed interface MinecraftConstants permits MinecraftServer {
    String VERSION_NAME = "26.4-snapshot-2";

    int PROTOCOL_VERSION = 1073742164;

    int DATA_VERSION = 5120;

    MajorMinorVersion RESOURCE_PACK_VERSION = new MajorMinorVersion(99, 0);

    MajorMinorVersion DATA_PACK_VERSION = new MajorMinorVersion(122, 1);
}
