package net.minestom.server;

import net.minestom.server.utils.MajorMinorVersion;

/**
 * This class contains all the generated constants for {@link MinecraftServer}
 * <br>
 * Code autogenerated, do not edit!
 */
sealed interface MinecraftConstants permits MinecraftServer {
    String VERSION_NAME = "26.3-snapshot-9";

    int PROTOCOL_VERSION = 1073742155;

    int DATA_VERSION = 5011;

    MajorMinorVersion RESOURCE_PACK_VERSION = new MajorMinorVersion(96, 0);

    MajorMinorVersion DATA_PACK_VERSION = new MajorMinorVersion(117, 0);
}
