{
  "formatVersion": "1.1",
  "component": {
    "group": "net.flowstom",
    "module": "nightstorm",
    "version": "2026.07.22-26.3-snapshot-6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.1.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-ansi",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "nightstorm-2026.07.22-26.3-snapshot-6.jar",
          "url": "nightstorm-2026.07.22-26.3-snapshot-6.jar",
          "size": 4222873,
          "sha512": "bdfb3d312a7569349ada11b034edb7b7b0ddddf6a6b625fe68b85a0b5187fd8183956040398b24341904469dd44636e32318aad6aabc118f451b61b9dc811fcf",
          "sha256": "bc61bef5a5184b4dc426b738c58b6beaf66d3f538bfef64c5a83853aea481fd5",
          "sha1": "2304c3520627cfc213da769b387b16c0bf876dcf",
          "md5": "408cdc4a872d400276b0b81cfa5229e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.18"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.18"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "space.vectrix.flare",
          "module": "flare",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "space.vectrix.flare",
          "module": "flare-fastutil",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "org.jctools",
          "module": "jctools-core-jdk11",
          "version": {
            "requires": "4.0.6"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.1.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-ansi",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.flowstom",
          "module": "nightstorm-data",
          "version": {
            "requires": "2026.07.22-26.3-snapshot-6"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "nightstorm-2026.07.22-26.3-snapshot-6.jar",
          "url": "nightstorm-2026.07.22-26.3-snapshot-6.jar",
          "size": 4222873,
          "sha512": "bdfb3d312a7569349ada11b034edb7b7b0ddddf6a6b625fe68b85a0b5187fd8183956040398b24341904469dd44636e32318aad6aabc118f451b61b9dc811fcf",
          "sha256": "bc61bef5a5184b4dc426b738c58b6beaf66d3f538bfef64c5a83853aea481fd5",
          "sha1": "2304c3520627cfc213da769b387b16c0bf876dcf",
          "md5": "408cdc4a872d400276b0b81cfa5229e8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nightstorm-2026.07.22-26.3-snapshot-6-sources.jar",
          "url": "nightstorm-2026.07.22-26.3-snapshot-6-sources.jar",
          "size": 1510637,
          "sha512": "6b54cb904f30a39960554b5487ce6e44116f974d9f6e6b9d8605a4f5737b53ea8b328e0581104ded54f061ae53f5873666bc0f2dd4ca05ab263d6fda00af4bc2",
          "sha256": "476071ad0878ec470362455cca24a09755fee17521619d3052ed3eedca5dd36a",
          "sha1": "6b9e1e2831606b98af554b079f630d65e01b7ebc",
          "md5": "33f16d486bc1147b9dbe65561cd9360d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nightstorm-2026.07.22-26.3-snapshot-6-javadoc.jar",
          "url": "nightstorm-2026.07.22-26.3-snapshot-6-javadoc.jar",
          "size": 13981019,
          "sha512": "96a8924c145e1a82379c37ddc4d2fc3586aff917fa8dd8fee97f31de632908f1435c7646a7cbaf058c6322b63343ed55c6c3c42a6ad79f809ba77c636f33796c",
          "sha256": "4d6aaff9771b44bbfacac17eff63eed8a7102797b24078ad1beffeae88e908d3",
          "sha1": "50dcb0cc3a103d3ba0c02c25396f91cb984a5860",
          "md5": "43bcc79a40fbfc6405c106c0c3f9e094"
        }
      ]
    }
  ]
}
