#!/usr/bin/env bash
set -euo pipefail

plan_file=${1:?usage: prepare-source.sh <plan.json> <target-directory>}
target_directory=${2:?usage: prepare-source.sh <plan.json> <target-directory>}
nightstorm_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

read_plan() {
  jq -r "$1" "$plan_file"
}

minecraft_version=$(read_plan '.minecraftVersion')
minestom_repository=$(read_plan '.minestomRepository')
minestom_tag=$(read_plan '.minestomTag')
data_generator_repository=$(read_plan '.minestomDataGeneratorRepository')
data_generator_commit=$(read_plan '.minestomDataGeneratorCommit')
base_ref=$(read_plan '.baseRef')

rm -rf "$target_directory"
mkdir -p "$(dirname "$target_directory")"

if [[ "$base_ref" == "$minestom_tag" ]]; then
  git clone --branch "$minestom_tag" "https://github.com/${minestom_repository}.git" "$target_directory"
  # A stream starts as a source snapshot. Importing Minestom's Git history would also import
  # upstream workflow commits, which the GitHub Actions token cannot push to this repository.
  rm -rf "$target_directory/.git" "$target_directory/.github/workflows"
  git -C "$target_directory" init
  git -C "$target_directory" add --all
  git -C "$target_directory" \
    -c user.name="github-actions[bot]" \
    -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
    commit -m "Minestom $minestom_tag"
else
  : "${NIGHTSTORM_REPOSITORY:?NIGHTSTORM_REPOSITORY is required when continuing a Nightstorm stream}"
  git clone --branch "$base_ref" "https://github.com/${NIGHTSTORM_REPOSITORY}.git" "$target_directory"
fi

data_generator_directory="${target_directory}.data-generator"
rm -rf "$data_generator_directory"
git clone "https://github.com/${data_generator_repository}.git" "$data_generator_directory"
git -C "$data_generator_directory" checkout --detach "$data_generator_commit"
bash "$nightstorm_root/scripts/install-registry-sync.sh" "$data_generator_directory" "$target_directory"
bash "$nightstorm_root/scripts/install-data-generator-compat.sh" "$data_generator_directory"

# MinestomDataGenerator is Minestom's existing bridge from vanilla data to its code generators.
if [[ "$base_ref" == "$minestom_tag" ]]; then
  baseline_minecraft_version=$(perl -ne 'print "$1\n" if /^data = "([^-\"]+)/' \
    "$target_directory/gradle/libs.versions.toml")
else
  baseline_minecraft_version=$(perl -ne 'print "$1\n" if /VERSION_NAME\s*=\s*"([^"]+)"/' \
    "$target_directory/src/autogenerated/java/net/minestom/server/MinecraftConstants.java")
fi
test -n "$baseline_minecraft_version"
perl -0pi -e 's/^minecraft = ".*"/minecraft = "'"$baseline_minecraft_version"'"/m' "$data_generator_directory/gradle/libs.versions.toml"
pushd "$data_generator_directory" >/dev/null
NIGHTSTORM_MINSTOM_SOURCE="$target_directory" EULA=true ./gradlew generateData --no-daemon
popd >/dev/null
baseline_server_jar="$HOME/.gradle/caches/fabric-loom/minecraftMaven/net/minecraft/minecraft-server-deobf/$baseline_minecraft_version/minecraft-server-deobf-$baseline_minecraft_version.jar"
test -f "$baseline_server_jar"
mkdir -p "$target_directory/.nightstorm"
cp "$baseline_server_jar" "$target_directory/.nightstorm/baseline-minecraft-server.jar"

perl -0pi -e 's/^minecraft = ".*"/minecraft = "'"$minecraft_version"'"/m' "$data_generator_directory/gradle/libs.versions.toml"
pushd "$data_generator_directory" >/dev/null
NIGHTSTORM_MINSTOM_SOURCE="$target_directory" EULA=true ./gradlew generateData --no-daemon
NIGHTSTORM_MINSTOM_SOURCE="$target_directory" EULA=true ./gradlew jar --no-daemon
popd >/dev/null

data_jar=$(ls "$data_generator_directory/build/libs/"*.jar)
cp "$data_jar" "$target_directory/.nightstorm/data.jar"

# Use the generated data as a named module instead of copying its resources into Minestom's modules.
perl -0pi -e 's/implementation\(libs\.minestomData\)/implementation(files(rootProject.file(".nightstorm\/data.jar")))/g' \
  "$target_directory/build.gradle.kts" "$target_directory/code-generators/build.gradle.kts"

# External Javadoc links are documentation-only and make releases depend on javadoc.io serving
# the legacy package-list file expected by the JDK's Javadoc tool.
perl -ni -e 'print unless /links\("https:\/\/javadoc\.io\//' \
  "$target_directory/build-src/src/main/kotlin/minestom.java-library.gradle.kts"

printf '%s\n' "$(perl -ne 'print "$1\n" if /JAVA_VERSION.*?:.*?"([0-9]+)"/' "$target_directory/build-src/src/main/kotlin/minestom.java-library.gradle.kts")" > "$target_directory/.nightstorm/java-version"
test -s "$target_directory/.nightstorm/java-version"
