{
  "formatVersion": "1.1",
  "component": {
    "group": "net.flowstom",
    "module": "nightstorm",
    "version": "2026.07.22-26.3-snapshot-5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.1.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-ansi",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "nightstorm-2026.07.22-26.3-snapshot-5.jar",
          "url": "nightstorm-2026.07.22-26.3-snapshot-5.jar",
          "size": 4222874,
          "sha512": "3bea2350f87306377069f157c972eaab0f18d47092ec113285f7fa318ace32ba52bc8a13dbcca15edc7339c85d72300c97c680a285bf1cea126630e570dd7179",
          "sha256": "2c915ea527176de0fca3cededfddfd7598f1b6cc0e8cb630b5b6039f5f071675",
          "sha1": "fd189595934057d91e52fa169e37c15dcbc3d5e0",
          "md5": "988d9141513a33167397b59b98aabc88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.18"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.18"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "space.vectrix.flare",
          "module": "flare",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "space.vectrix.flare",
          "module": "flare-fastutil",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "org.jctools",
          "module": "jctools-core-jdk11",
          "version": {
            "requires": "4.0.6"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.1.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-nbt",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-ansi",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        },
        {
          "group": "net.flowstom",
          "module": "nightstorm-data",
          "version": {
            "requires": "2026.07.22-26.3-snapshot-5"
          },
          "excludes": [
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "nightstorm-2026.07.22-26.3-snapshot-5.jar",
          "url": "nightstorm-2026.07.22-26.3-snapshot-5.jar",
          "size": 4222874,
          "sha512": "3bea2350f87306377069f157c972eaab0f18d47092ec113285f7fa318ace32ba52bc8a13dbcca15edc7339c85d72300c97c680a285bf1cea126630e570dd7179",
          "sha256": "2c915ea527176de0fca3cededfddfd7598f1b6cc0e8cb630b5b6039f5f071675",
          "sha1": "fd189595934057d91e52fa169e37c15dcbc3d5e0",
          "md5": "988d9141513a33167397b59b98aabc88"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nightstorm-2026.07.22-26.3-snapshot-5-sources.jar",
          "url": "nightstorm-2026.07.22-26.3-snapshot-5-sources.jar",
          "size": 1510637,
          "sha512": "bbbca3d21badcdfcaff5669f2e5f7b30d9d104c5441f575c7eca4f6ec2d8cb9719c6fbb73e42eda93709dcbdf9efc1bcfc4b3ab52189c335ccf04383f653cfb1",
          "sha256": "13046febc1e9e3a712520e140c6407f6e9356bb282ff00236daa4a65f2c21053",
          "sha1": "7036233ca082f84644c91fd1712b999c2789a0f1",
          "md5": "ed140d8073f21db36115af22dd37ce17"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nightstorm-2026.07.22-26.3-snapshot-5-javadoc.jar",
          "url": "nightstorm-2026.07.22-26.3-snapshot-5-javadoc.jar",
          "size": 13981021,
          "sha512": "56678b8335b77f9822dd60c96c00a80866eb0950ceae5ef4de81c16d3d07d8d34980fc8db39b7d5c5c644b9ef2b6a18470bbd9cd3f0cbfd9c443911e9788455c",
          "sha256": "e7f501c1b2943027a900b224e892b2bb7140969794c55c4d9a6f7ae15f6f8dd3",
          "sha1": "dd7ea7753faf3315f464145e20343a4ec811c52e",
          "md5": "8a9728eef9e5973f444f6b2679a5d0f2"
        }
      ]
    }
  ]
}
